// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG67AwhiKAXQxxgMXjtyN7_2xvZ66Dozg',
    appId: '1:13569667234:web:b08c10452f524eb097a7fb',
    messagingSenderId: '13569667234',
    projectId: 'todevelopourlist',
    authDomain: 'todevelopourlist.firebaseapp.com',
    storageBucket: 'todevelopourlist.appspot.com',
    measurementId: 'G-13ME9054HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSrrjP_HYU6U951yskqdQutZAlk5ZGv4',
    appId: '1:13569667234:android:412f6bafd14b39b797a7fb',
    messagingSenderId: '13569667234',
    projectId: 'todevelopourlist',
    storageBucket: 'todevelopourlist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJG38w185FqjCZKstkjnrMdC41e1ay5A',
    appId: '1:13569667234:ios:23fbcfa5ce2d7cef97a7fb',
    messagingSenderId: '13569667234',
    projectId: 'todevelopourlist',
    storageBucket: 'todevelopourlist.appspot.com',
    iosBundleId: 'com.example.todevelopourlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJG38w185FqjCZKstkjnrMdC41e1ay5A',
    appId: '1:13569667234:ios:23fbcfa5ce2d7cef97a7fb',
    messagingSenderId: '13569667234',
    projectId: 'todevelopourlist',
    storageBucket: 'todevelopourlist.appspot.com',
    iosBundleId: 'com.example.todevelopourlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG67AwhiKAXQxxgMXjtyN7_2xvZ66Dozg',
    appId: '1:13569667234:web:d0024478d1ba6af197a7fb',
    messagingSenderId: '13569667234',
    projectId: 'todevelopourlist',
    authDomain: 'todevelopourlist.firebaseapp.com',
    storageBucket: 'todevelopourlist.appspot.com',
    measurementId: 'G-F9881G0KBJ',
  );
}
